name: Effective-Campaigning
version: 0.1.0.0
github: "Per48edjes/Effective-Campaigning"
license: BSD3
author: "Ravi Dayabhai"
maintainer: "r.i.dayabhai@gmail.com"
copyright: "2023 Ravi Dayabhai"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Simple implementation vis-a-vis Q1, PSET 7 from MIT 6.006 (Spring 2020)

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - memoize
    - vector

tests:
  Effective-Campaigning-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Effective-Campaigning
      - hspec
      - vector
      - memoize
